name: Generate Snake Game

on:
  schedule:
    - cron: "0 0 * * *" # roda todo dia à meia-noite (UTC)
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      - name: Gera a cobrinha com base nas contribuições
        uses: Platane/snk@v3
        with:
          github_user_name: RuasCardi
          outputs: dist/github-contribution-grid-snake.svg

      - name: Faz o commit do resultado
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
